parameters:
  - name: feedToPublish
    type: string
  - name: feedVersion
    type: 'string'

stages:
  - stage: publish
    dependsOn: build
    jobs:
      - job: publishTerraform    
        pool: 
          vmImage: windows-latest
        steps:
        - download: current
          artifact: 'drop'
          name: 'Download_Terraform_code'
          displayName: 'Download Terraform code'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              
              Write-Host "Show downloaded files"
              
              Get-ChildItem $(Pipeline.Workspace)  -Recurse
          displayName: 'Output files'
        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Pipeline.Workspace)/drop/'
            vstsFeedPublish: '${{ parameters.feedToPublish }}'
            vstsFeedPackagePublish: 'storage-account'
            versionOption: '${{ parameters.feedVersion }}'