name: 1.0$(Rev:.r)

trigger:
- main

variables:
- template: variables-pipeline.yml

stages:
  - template: Stages/build.yml
  - template: Stages/publish.yml
    parameters:
      feedToPublish: 'Terraform-Modules-Release'
      feedVersion: 'major' # ##### This is key ####### options are here (major, minor, patch)